/**
 * PDF Export Utility
 *
 * Generates a print-ready HTML document from proposal data.
 * Single responsibility: proposal → printable HTML → browser print dialog.
 */

const THEME = {
  primary: '#c8a96e',
  primaryLight: '#d4b87a',
  gradient: 'linear-gradient(135deg, #c8a96e, #d4b87a)',
  textDark: '#1a1a1a',
  textMedium: '#444444',
  textLight: '#666666',
  textMuted: '#999999',
  border: '#e5e5e5',
  background: '#ffffff',
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
}

/**
 * Build the HTML for a single proposal section.
 */
function buildSectionHtml(section, index) {
  return `
    <div style="margin-bottom: 32px;">
      <h2 style="font-size: 20px; font-weight: 700; color: ${THEME.textDark}; margin-bottom: 12px; display: flex; align-items: center; gap: 10px;">
        <span style="display: inline-flex; align-items: center; justify-content: center; width: 32px; height: 32px; background: ${THEME.gradient}; color: #000000; border-radius: 8px; font-size: 14px; font-weight: 700; flex-shrink: 0;">${index + 1}</span>
        ${section.heading}
      </h2>
      <div style="color: ${THEME.textMedium}; line-height: 1.8; white-space: pre-line; padding-left: 42px;">${section.content}</div>
    </div>
  `
}

/**
 * Build the full HTML document for printing.
 */
function buildPrintDocument(proposal, sectionsHtml) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${proposal.title}</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: ${THEME.fontFamily};
          color: ${THEME.textDark};
          background: ${THEME.background};
          padding: 60px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          text-align: center;
          border-bottom: 2px solid ${THEME.border};
          padding-bottom: 32px;
          margin-bottom: 40px;
        }
        .logo-box {
          display: inline-flex;
          align-items: center;
          justify-content: center;
          width: 56px;
          height: 56px;
          background: ${THEME.gradient};
          border-radius: 12px;
          margin-bottom: 16px;
        }
        .logo-box svg {
          width: 28px;
          height: 28px;
          color: #000000;
          stroke: #000000;
          fill: none;
          stroke-width: 2;
        }
        h1 {
          font-size: 28px;
          font-weight: 800;
          color: ${THEME.textDark};
          margin-bottom: 8px;
        }
        .subtitle {
          font-size: 16px;
          color: ${THEME.textLight};
          font-weight: 400;
        }
        .date {
          font-size: 13px;
          color: ${THEME.textMuted};
          margin-top: 4px;
        }
        .footer {
          margin-top: 60px;
          padding-top: 24px;
          border-top: 1px solid ${THEME.border};
          text-align: center;
          font-size: 12px;
          color: ${THEME.textMuted};
        }
        .footer p { margin-bottom: 4px; }
        @media print {
          body { padding: 40px; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo-box">
          <svg viewBox="0 0 24 24" stroke="currentColor" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
        </div>
        <h1>${proposal.title}</h1>
        <p class="subtitle">${proposal.subtitle}</p>
        <p class="date">${proposal.date}</p>
      </div>
      <div class="sections">${sectionsHtml}</div>
      <div class="footer">
        <p>This proposal was generated by BidEngine AI — ${proposal.date}</p>
        <p>Confidential — For authorized recipients only</p>
      </div>
      <div class="no-print" style="position: fixed; bottom: 20px; right: 20px;">
        <button onclick="window.print()" style="padding: 12px 24px; background: ${THEME.gradient}; color: #000000; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; font-size: 14px; box-shadow: 0 4px 15px rgba(226, 165, 54, 0.3);">
          Save as PDF
        </button>
      </div>
    </body>
    </html>
  `
}

/**
 * Export a proposal as a printable PDF document.
 *
 * Opens a new window with the proposal formatted for printing.
 * The user can then use the browser's "Save as PDF" option.
 *
 * @param {Object} proposal - Proposal object with title, subtitle, date, sections[]
 */
export function exportProposalPdf(proposal) {
  if (!proposal || !proposal.sections) return

  const sectionsHtml = proposal.sections
    .map((section, i) => buildSectionHtml(section, i))
    .join('')

  const html = buildPrintDocument(proposal, sectionsHtml)

  const printWindow = window.open('', '_blank')
  printWindow.document.write(html)
  printWindow.document.close()
}
